# Generated by Django 4.1.7 on 2023-04-11 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAnh',
            fields=[
                ('images_id', models.AutoField(primary_key=True, serialize=False)),
                ('images_name', models.CharField(max_length=50, null=True)),
                ('images_level', models.IntegerField()),
                ('images_path', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagespath', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('predicted', models.TextField()),
                ('confidence', models.IntegerField(blank=True, default=0, null=True)),
                ('saved', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-saved',),
            },
        ),
    ]
