# Generated by Django 4.1.7 on 2023-04-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThoBayMau', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileanh',
            name='images_path',
        ),
        migrations.AlterField(
            model_name='fileanh',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
