# Generated by Django 4.2 on 2023-04-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThoBayMau', '0002_remove_fileanh_images_path_alter_fileanh_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='bacsi',
            fields=[
                ('bacsi_id', models.AutoField(primary_key=True, serialize=False)),
                ('bacsi_name', models.CharField(max_length=150)),
                ('bacsi_age', models.IntegerField(null=True)),
                ('bacsi_locate', models.CharField(max_length=150, null=True)),
                ('bacsi_position', models.CharField(max_length=150, null=True)),
                ('bacsi_content', models.CharField(max_length=2500, null=True)),
                ('bacsi_avatar', models.ImageField(default=None, null=True, upload_to='images')),
            ],
        ),
    ]
