# Generated by Django 4.2 on 2023-04-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThoBayMau', '0003_bacsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacsi',
            name='bacsi_avatar',
            field=models.ImageField(default=None, null=True, upload_to='images_bacsi'),
        ),
    ]
