# Generated by Django 4.2 on 2023-04-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThoBayMau', '0005_benhnhan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhnhan',
            name='benhnhan_sdt',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
