# Generated by Django 4.2 on 2023-04-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThoBayMau', '0006_alter_benhnhan_benhnhan_sdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='benhnhan',
            name='benhnhan_status',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='benhnhan',
            name='benhnhan_email',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
